### ISSUE TITLE
core/models.py - __future__

### ISSUE THREAD

**Issue by hpfn** [vmdesenvolvimento/certgen#90]
Enviando a msg por aqui porque o Slack simplesmente não carrega.

O arquivo 'core/models.py' faz uso do módulo '__future__'.  E também 
importa o 'ugettext_lazy' do Django - linha 9.

A partir da versão 2.0 o Django não suporta Python 2. O prefixo 'u'
é usado quando o código tem suporte a Python 2.

Usando 'gettext_lazy' pode ser que o módulo '__future__' não seja
necessário.

**Comment by joaogarciadelima** [comment]
Blz Hebert vou retirar aqui e já mando um PR corrigindo.
